[package]
name = "app"
version = "0.1.0"
authors = ["Tyler Jensen <tyler@tsjensen.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "app"
path = "./app.rs"

[dependencies]
chrono = "0.4"